# sudo is required for super user level access when using docker
sudo: required

#services which the Travis CI will need for your project , in this case docker is required on Travis CI. Behind the Scenes it will install DOcker
services:
    - docker

#before install to run docker build commands. These commands are run 
before_install:
    - docker build -t vaibhav09dev/docker-react-frontend -f Dockerfile.dev .

#script - all the commands that need to be executed to run our tests / deployment
script:
    - docker run vaibhav09dev/docker-react-frontend npm run test -- --coverage

# Configuration to deploy code on AWS through Travis
#bucket_name is the s3 bucket which is automatically created when u create elasticbeanstalk
#access_key_id and secret is created after creating user in IAM Module in AWS console. These values are stored in travis environment variable
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react-frontend"
    env: "DockerReactFrontend-env"
    bucket_name: "elasticbeanstalk-us-east-2-588495759203"
    bucket_path: "docker-react-frontend"
    on: 
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_SECRET_KEY"